-- =====================================================
-- 리원피부과 통합 Supabase 스키마
-- 생성일: 2025-12-25
-- 버전: 1.0
-- 설명: 다른 병원에서 한 번에 복사하여 사용할 수 있는 통합 SQL
-- =====================================================
-- 
-- 사용 방법:
-- 1. Supabase 프로젝트를 새로 생성합니다
-- 2. SQL Editor에서 이 파일 전체를 실행합니다
-- 3. 필요에 따라 병원명, 의사명 등을 수정합니다
--
-- 주의사항:
-- - 기존 데이터가 있는 프로젝트에서 실행 시 충돌이 발생할 수 있습니다
-- - 새 프로젝트에서 처음부터 실행하는 것을 권장합니다
-- =====================================================

-- =====================================================
-- SECTION 1: EXTENSIONS
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- SECTION 2: HELPER FUNCTIONS
-- =====================================================

-- is_staff() 함수: 스태프 여부 확인 (RLS 정책에서 사용)
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.staff_users
    WHERE user_id = auth.uid()
    AND role IN ('doctor', 'staff', 'admin')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- SECTION 3: CORE TABLES - Users & Profiles
-- =====================================================

-- 3.1 환자 프로필 (Auth User와 연결)
CREATE TABLE IF NOT EXISTS public.patient_profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  phone_normalized TEXT,
  date_of_birth DATE,
  gender TEXT,
  lifecycle_stage TEXT DEFAULT 'lead',  -- 'lead', 'new', 'returning', 'vip'
  source TEXT,                           -- 유입 경로
  first_contact_at TIMESTAMPTZ,
  last_visit_at TIMESTAMPTZ,
  total_visits INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT patient_profiles_phone_normalized_key UNIQUE (phone_normalized)
);

-- 3.2 스태프 사용자 (의사, 직원, 관리자)
CREATE TABLE IF NOT EXISTS public.staff_users (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT CHECK (role IN ('doctor', 'staff', 'admin')),
  display_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.3 환자 테이블 (CRM 핵심 - 오프라인 환자 포함)
CREATE TABLE IF NOT EXISTS public.patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,  -- Supabase Auth 사용자 연결
  naver_user_id TEXT,                 -- NextAuth 네이버 사용자 ID (이메일 미제공)
  name TEXT NOT NULL,
  time TEXT,                    -- 예약 시간 정보 (레거시)
  type TEXT,                    -- 환자 유형
  complaint TEXT,               -- 주호소
  keywords TEXT[],              -- 키워드 배열
  status TEXT CHECK (status IN ('pending', 'completed', 'cancelled')) DEFAULT 'pending',
  email TEXT,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 환자 인덱스
CREATE INDEX IF NOT EXISTS idx_patients_user_id ON public.patients(user_id);
CREATE INDEX IF NOT EXISTS idx_patients_naver_user_id ON public.patients(naver_user_id);

-- =====================================================
-- SECTION 4: APPOINTMENT SYSTEM
-- =====================================================

-- 4.1 예약 슬롯
CREATE TABLE IF NOT EXISTS public.appointment_slots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  department TEXT,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  start_time TIMESTAMPTZ,           -- 호환성 컬럼
  end_time TIMESTAMPTZ,             -- 호환성 컬럼
  capacity INT NOT NULL DEFAULT 1,
  booked INT NOT NULL DEFAULT 0,
  is_available BOOLEAN DEFAULT TRUE,
  current_bookings INTEGER DEFAULT 0,
  max_bookings INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4.2 예약
CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT REFERENCES public.patients(id) ON DELETE SET NULL,
  slot_id UUID REFERENCES public.appointment_slots(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  scheduled_at TIMESTAMPTZ NOT NULL,
  doctor_name VARCHAR(100),         -- 담당 의사
  naver_user_id TEXT,               -- 네이버 로그인 사용자 ID
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 예약 인덱스
CREATE INDEX IF NOT EXISTS idx_appointments_patient_id ON public.appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_naver_user_id ON public.appointments(naver_user_id);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor_date ON public.appointments (doctor_name, scheduled_at) WHERE status != 'cancelled';

-- =====================================================
-- SECTION 5: HEALTH DATA SYSTEM
-- =====================================================

-- 5.1 진료 방문 기록
CREATE TABLE IF NOT EXISTS public.visits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  visit_type TEXT,  -- 'first', 'revisit', 'online'
  status TEXT,      -- 'scheduled', 'completed', 'canceled'
  scheduled_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5.2 건강 토픽 (상담 주제)
CREATE TABLE IF NOT EXISTS public.health_topics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  topic_key TEXT UNIQUE NOT NULL,  -- 'skincare', 'acne', 'aging' 등
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5.3 건강 질문
CREATE TABLE IF NOT EXISTS public.health_questions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  topic_id UUID REFERENCES public.health_topics(id) ON DELETE CASCADE,
  question_key TEXT NOT NULL,
  text TEXT NOT NULL,
  input_type TEXT,        -- 'text', 'choice', 'scale'
  options JSONB,          -- 선택지
  mode TEXT DEFAULT 'healthcare',  -- 'healthcare', 'medical'
  version INT DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- SECTION 6: CHAT/INTAKE SYSTEM
-- =====================================================

-- 6.1 채팅 세션
CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  anonymous_id TEXT,      -- 비로그인 사용자용
  mode TEXT,              -- 'healthcare', 'medical'
  topic TEXT,             -- topic_key
  visit_id UUID REFERENCES public.visits(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6.2 채팅 메시지
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id UUID REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  sender TEXT,            -- 'user', 'ai', 'system'
  content TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6.3 인테이크 세션
CREATE TABLE IF NOT EXISTS public.intake_sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  patient_id BIGINT REFERENCES public.patients(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active',
  turn_count INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6.4 인테이크 메시지
CREATE TABLE IF NOT EXISTS public.intake_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id UUID NOT NULL REFERENCES public.intake_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6.5 인테이크 근거자료
CREATE TABLE IF NOT EXISTS public.intake_evidence (
  session_id UUID PRIMARY KEY REFERENCES public.intake_sessions(id) ON DELETE CASCADE,
  evidence_json JSONB,
  red_flags JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6.6 인테이크 답변
CREATE TABLE IF NOT EXISTS public.intake_answers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id UUID REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  question_id UUID REFERENCES public.health_questions(id) ON DELETE SET NULL,
  question_key TEXT,
  raw_answer TEXT,
  normalized JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6.7 인테이크 요약
CREATE TABLE IF NOT EXISTS public.intake_summaries (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  visit_id UUID REFERENCES public.visits(id) ON DELETE SET NULL,
  session_id UUID REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  main_concern TEXT,
  pattern_tags TEXT[],
  rhythm_score INT,
  rhythm_score_detail JSONB,
  summary_text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- SECTION 7: CLINICAL DATA
-- =====================================================

-- 7.1 진료 노트
CREATE TABLE IF NOT EXISTS public.clinical_notes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  visit_id UUID REFERENCES public.visits(id) ON DELETE CASCADE,
  note_type TEXT,        -- 'soap', 'memo'
  title TEXT,
  body TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7.2 치료 계획
CREATE TABLE IF NOT EXISTS public.treatment_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  visit_id UUID REFERENCES public.visits(id) ON DELETE CASCADE,
  plan_type TEXT,        -- 'procedure', 'medication', 'lifestyle'
  title TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7.3 임상 이미지
CREATE TABLE IF NOT EXISTS public.clinical_images (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  visit_id UUID REFERENCES public.visits(id) ON DELETE SET NULL,
  session_id UUID REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  image_url TEXT NOT NULL,
  thumbnail_url TEXT,
  body_part TEXT,
  description TEXT,
  ai_summary TEXT,
  ai_metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- SECTION 8: NOTIFICATIONS & MESSAGING
-- =====================================================

-- 8.1 알림
CREATE TABLE IF NOT EXISTS public.reminders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  visit_id UUID REFERENCES public.visits(id) ON DELETE SET NULL,
  title TEXT,
  schedule_at TIMESTAMPTZ,
  is_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8.2 메시지 작업큐
CREATE TABLE IF NOT EXISTS public.message_jobs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  channel TEXT NOT NULL,          -- 'alimtalk', 'sms', 'push'
  template_code TEXT NOT NULL,
  payload JSONB,
  scheduled_for TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'queued',  -- 'queued', 'processing', 'sent', 'failed'
  sent_at TIMESTAMPTZ,
  retry_count INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8.3 푸시 토큰
CREATE TABLE IF NOT EXISTS public.push_tokens (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios', 'web')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, token)
);

-- =====================================================
-- SECTION 9: CONSENTS & AUDIT
-- =====================================================

-- 9.1 동의서
CREATE TABLE IF NOT EXISTS public.consents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,             -- 'privacy', 'marketing', 'third_party'
  agreed BOOLEAN NOT NULL DEFAULT FALSE,
  agreed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9.2 감사 로그
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  actor_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  entity_table TEXT,
  entity_id UUID,
  action TEXT,                    -- 'view', 'create', 'update', 'delete'
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- SECTION 10: MARKETING TRACKING
-- =====================================================

-- 10.1 마케팅 이벤트
CREATE TABLE IF NOT EXISTS public.marketing_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  visitor_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  user_id UUID NULL,
  event_name TEXT NOT NULL,
  page_url TEXT NULL,
  landing_url TEXT NULL,
  referrer TEXT NULL,
  utm_source TEXT NULL,
  utm_medium TEXT NULL,
  utm_campaign TEXT NULL,
  utm_content TEXT NULL,
  utm_term TEXT NULL,
  sub1 TEXT NULL,
  sub2 TEXT NULL,
  click_ids JSONB NULL,
  user_agent TEXT NULL,
  device_type TEXT NULL,
  login_source TEXT NULL,
  prompt_version_id TEXT NULL,
  flow_version_id TEXT NULL,
  metadata JSONB NULL
);

-- 10.2 마케팅 전환
CREATE TABLE IF NOT EXISTS public.marketing_conversions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID NULL,
  visitor_id TEXT NULL,
  reservation_id TEXT NOT NULL UNIQUE,
  attributed_event_id UUID NULL,
  last_touch JSONB NOT NULL,
  first_touch JSONB NULL,
  path_summary TEXT NULL,
  conversion_time_seconds INT NULL
);

-- 10.3 UTM 링크
CREATE TABLE IF NOT EXISTS public.utm_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID NULL,
  channel TEXT NOT NULL,
  landing_url TEXT NOT NULL,
  final_url TEXT NOT NULL,
  utm_source TEXT NOT NULL,
  utm_medium TEXT NOT NULL,
  utm_campaign TEXT NOT NULL,
  utm_content TEXT NOT NULL,
  utm_term TEXT NULL,
  sub1 TEXT NULL,
  sub2 TEXT NULL,
  memo TEXT NULL
);

-- 마케팅 인덱스
CREATE INDEX IF NOT EXISTS idx_marketing_events_created ON public.marketing_events(created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_events_name ON public.marketing_events(event_name, created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_events_visitor ON public.marketing_events(visitor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_events_user ON public.marketing_events(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_events_utm ON public.marketing_events(utm_source, utm_campaign, created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_conversions_created ON public.marketing_conversions(created_at);
CREATE INDEX IF NOT EXISTS idx_marketing_conversions_user ON public.marketing_conversions(user_id, created_at);

-- =====================================================
-- SECTION 11: ROW LEVEL SECURITY (RLS)
-- =====================================================

-- 11.1 RLS 활성화
ALTER TABLE public.patient_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointment_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.utm_links ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- SECTION 12: RLS POLICIES
-- =====================================================

-- 12.1 Patient Profiles
CREATE POLICY "Users can view own profile" ON public.patient_profiles 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON public.patient_profiles 
  FOR UPDATE USING (auth.uid() = user_id);

-- 12.2 Staff Users
CREATE POLICY "Users can view own staff role" ON public.staff_users 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Staff can view all staff" ON public.staff_users 
  FOR SELECT USING (public.is_staff());

-- 12.3 Patients
CREATE POLICY "Enable read access for all users" ON public.patients 
  FOR SELECT USING (TRUE);
CREATE POLICY "Enable update for all users" ON public.patients 
  FOR UPDATE USING (TRUE);
CREATE POLICY "Enable insert for API access" ON public.patients 
  FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Users can view own patient record" ON public.patients 
  FOR SELECT USING (auth.uid() = user_id OR TRUE);
CREATE POLICY "Users can update own patient record" ON public.patients 
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Authenticated users can insert patients" ON public.patients 
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- 12.4 Visits
CREATE POLICY "Users can view own visits" ON public.visits 
  FOR SELECT USING (auth.uid() = user_id);

-- 12.5 Chat Sessions & Messages
CREATE POLICY "Users can view own sessions" ON public.chat_sessions 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own messages" ON public.chat_messages 
  FOR SELECT USING (
    session_id IN (SELECT id FROM chat_sessions WHERE user_id = auth.uid() OR anonymous_id IS NOT NULL)
  );

-- 12.6 Clinical Notes & Treatment Plans
CREATE POLICY "Staff can manage clinical notes" ON public.clinical_notes 
  FOR ALL USING (public.is_staff());
CREATE POLICY "Staff can manage treatment plans" ON public.treatment_plans 
  FOR ALL USING (public.is_staff());
CREATE POLICY "Patients can view own treatment plans" ON public.treatment_plans 
  FOR SELECT USING (
    visit_id IN (SELECT id FROM visits WHERE user_id = auth.uid())
  );

-- 12.7 Reminders
CREATE POLICY "Users can view own reminders" ON public.reminders 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Staff can manage reminders" ON public.reminders 
  FOR ALL USING (public.is_staff());

-- 12.8 Audit Logs
CREATE POLICY "Staff can view audit logs" ON public.audit_logs 
  FOR SELECT USING (public.is_staff());
CREATE POLICY "System can insert audit logs" ON public.audit_logs 
  FOR INSERT WITH CHECK (TRUE);

-- 12.9 Appointment Slots
CREATE POLICY "Anyone can view appointment slots" ON public.appointment_slots 
  FOR SELECT USING (TRUE);
CREATE POLICY "Staff can manage appointment slots" ON public.appointment_slots 
  FOR ALL USING (public.is_staff());

-- 12.10 Appointments
CREATE POLICY "Enable read access for appointments" ON public.appointments 
  FOR SELECT USING (TRUE);
CREATE POLICY "Enable insert for appointments" ON public.appointments 
  FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Enable update for appointments" ON public.appointments 
  FOR UPDATE USING (TRUE);
CREATE POLICY "Users can view own appointments" ON public.appointments 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own appointments" ON public.appointments 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff can manage all appointments" ON public.appointments 
  FOR ALL USING (public.is_staff());

-- 12.11 Intake Sessions & Messages
CREATE POLICY "Users can view own intake sessions" ON public.intake_sessions 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own intake sessions" ON public.intake_sessions 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff can view all intake sessions" ON public.intake_sessions 
  FOR SELECT USING (public.is_staff());
CREATE POLICY "Users can view own intake messages" ON public.intake_messages 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.intake_sessions 
      WHERE intake_sessions.id = intake_messages.session_id 
      AND intake_sessions.user_id = auth.uid()
    )
  );
CREATE POLICY "Staff can view all intake messages" ON public.intake_messages 
  FOR SELECT USING (public.is_staff());

-- 12.12 Consents
CREATE POLICY "Users can view own consents" ON public.consents 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own consents" ON public.consents 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 12.13 Push Tokens
CREATE POLICY "Users can manage own push tokens" ON public.push_tokens 
  FOR ALL USING (auth.uid() = user_id);

-- 12.14 Message Jobs
CREATE POLICY "Staff can manage message jobs" ON public.message_jobs 
  FOR ALL USING (public.is_staff());

-- 12.15 Marketing Events & Conversions
CREATE POLICY "Allow public insert events" ON public.marketing_events 
  FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Staff can select events" ON public.marketing_events 
  FOR SELECT USING (public.is_staff());
CREATE POLICY "Allow public insert conversions" ON public.marketing_conversions 
  FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Staff can select conversions" ON public.marketing_conversions 
  FOR SELECT USING (public.is_staff());

-- 12.16 UTM Links
CREATE POLICY "Staff can manage utm_links" ON public.utm_links 
  FOR ALL USING (public.is_staff());

-- =====================================================
-- SECTION 13: GRANTS
-- =====================================================
GRANT ALL ON public.appointment_slots TO authenticated;
GRANT ALL ON public.appointment_slots TO service_role;

-- =====================================================
-- SECTION 14: SCHEMA REFRESH
-- =====================================================
NOTIFY pgrst, 'reload schema';

-- =====================================================
-- 완료 메시지
-- =====================================================
DO $$
BEGIN
  RAISE NOTICE '============================================';
  RAISE NOTICE '통합 스키마 설치 완료!';
  RAISE NOTICE '테이블: 22개';
  RAISE NOTICE 'RLS 정책: 적용 완료';
  RAISE NOTICE '============================================';
END $$;
